[package]
name = "casemate-lib-macros"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0"

[dev-dependencies]
casemate = { path = "../casemate-lib" }
